apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: student-app
  namespace: bhavana
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: student-app
  template: 
    metadata: 
      labels: 
        app: student-app
    spec:
      containers:
        - name: student-app
          image: bhavana686/student-app:v1
          ports:
            - containerPort: 80
